In [2]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [4]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [14]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [22]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [24]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [26]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [28]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr)

[[1 2 3]
 [4 5 6]]


In [34]:
import numpy as np
arr1=np.array([1,3,5])
arr2=np.array([2,4,6])
result=np.dot(arr1,arr2)
print(result)

44


In [36]:
import numpy as np
arr1=np.array([[1,3],[5,7]])
arr2=np.array([[2,4],[6,8]])
result=np.inner(arr1,arr2)
print(result)

[[14 30]
 [38 86]]


In [38]:
import numpy as np
arr1=np.array([1,3,5])
arr2=np.array([2,4,6])
result=np.outer(arr1,arr2)
print(result)

[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


In [44]:
import numpy as np
arr1=np.array([[1,3],[5,7]])
result=np.linalg.det(arr1)
print(result)

-7.999999999999998


In [57]:
import numpy as np
a=np.array([[2,4],[6,8]])
b=np.array([5,6])
x=np.linalg.solve(a,b)
print(x)

[-2.    2.25]


In [59]:
import numpy as np
arr1=np.array([[2,4],[6,8]])
result=np.linalg.inv(arr1)
print(result)

[[-1.    0.5 ]
 [ 0.75 -0.25]]
