In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
ary=np.array([1,2,3,4,5])
ary

array([1, 2, 3, 4, 5])

In [3]:
type(ary)

numpy.ndarray

In [4]:
import numpy as np
ary1=np.array(12)
print(ary1)

12


In [5]:
import numpy as np
ary2=np.array([[1,2,3],[4,5,6]])
print(ary2)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
ary3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(ary3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
print(ary1.ndim)

0


In [8]:
import numpy as np
ary4=np.array([1,2,3,4],ndmin=5)
print(ary4)

[[[[[1 2 3 4]]]]]


In [9]:
import numpy as np
ary5=np.array([1,2,3,4])
print(ary5[2])

3


In [13]:
import numpy as np
ary6=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ary6[0,3])

4


In [15]:
print(ary6[1,4])

10


In [19]:
import numpy as np
ary7=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ary7[0,0:4])

[1 2 3 4]


In [28]:
import numpy as np
ary8=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(ary8[1,0,1])

8
