In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [7]:
import numpy as np

arr = np.array(12)

print(arr)

12


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
import numpy as np

arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [17]:
print(arr1.ndim)

3


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=32)

arr

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2,
                                      3, 4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2])

3


In [29]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[0,3]

4

In [31]:
arr[1,3]

9

In [33]:
arr[0,0:4]

array([1, 2, 3, 4])

In [35]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [37]:
arr[1,0,1]

8